#!/bin/sh
# Hotplug script for ModemManager events.  Place in /etc/hotplug.d/iface/30-keepalive_modemmanager
# and give execute permission.  
#
# Copyright 2019 Nicholas Smith <mips171@icloud.com>
#

if [ $INTERFACE = "mobiledata" ]; then
if [ $ACTION != "ifup" ]; then
MODEMIFACE="mobiledata"

# TODO get modem index dynamically
/usr/bin/mmcli -m 0 > /tmp/modemStatus 
DISABLED=$(cat /tmp/modemStatus | grep -w "disabled")
SEARCHING=$(cat /tmp/modemStatus | grep -w "searching")
REGISTERED=$(cat /tmp/modemStatus | grep -w "registered")
CONNECTED=$(cat /tmp/modemStatus | grep -w "connected")
IDLE=$(cat /tmp/modemStatus | grep -w "idle")

RUNNING="0" # A sort of lock

logger -t INFO "Hotplug: Checking if modem is connected."

if [ -n "$DISABLED" ]; then
	logger -t INFO	"Modem is disabled. Will attempt to initiate connection."
	logger -t DEBUG "$DISABLED"
	if [ "$RUNNING" -eq "0" ]; then
		$RUNNING="1"
		/etc/init.d/modemmanager stop && sleep 2 && /etc/init.d/modemmanager start
		ifup $MODEMIFACE
		$RUNNING="0"
	fi
fi

if [ -n "$CONNECTED" ]; then
	sleep 10
	if [ "$(/bin/ping -c 1 www.telcoantennas.com.au &> /dev/null ; echo $?)" -eq "1" ]; then
		if [ "$RUNNING" -eq "0" ]; then
			$RUNNING="1"
			logger -t INFO "Modem failed ping test. Reconnecting."
			/etc/init.d/modemmanager stop && sleep 2 && /etc/init.d/modemmanager start
			ifup $MODEMIFACE
			$RUNNING="0"
		fi
	else
		logger -t INFO "Modem is connected."
	fi
fi

if [ -n "$SEARCHING" ]; then
	if [ "$RUNNING" -eq "0" ]; then
		logger -t INFO "Modem is searching.  Attempting to bring modem back online."
		$RUNNING="1"
		/etc/init.d/modemmanager stop && sleep 2 && /etc/init.d/modemmanager start
		ifup $MODEMIFACE
		$RUNNING="0"
	else
		logger -t INFO "Modem is not searching."
	fi
fi

if [ -n "$IDLE" ]; then
	if [ "$RUNNING" -eq "0" ]; then
		$RUNNING="1"
		logger -t INFO "Modem is idle.  Attempting to bring modem back online."
		/etc/init.d/modemmanager stop && sleep 2 && /etc/init.d/modemmanager start
		ifup $MODEMIFACE
		$RUNNING="0"
	else 
		logger -t INFO "Modem is not idle."
	fi
fi

if [ -n "$REGISTERED" ]; then
	if [ "$RUNNING" -eq "0" ]; then
		$RUNNING="1"
		logger -t INFO "Modem is registered. Attempting to bring modem back online."
		/etc/init.d/modemmanager stop && sleep 2 && /etc/init.d/modemmanager start
		ifup $MODEMIFACE
		$RUNNING="0"
	else
		logger -t INFO "Modem is not registered."
	fi
fi
logger -t INFO "Modem hotplug script ran."
fi
fi
