#!/bin/sh
# Hotplug script for ModemManager events.  Place in /etc/hotplug.d/iface/30-keepalive_modemmanager
# and give execute permission.
#
# Copyright 2020 Nicholas Smith <mips171@icloud.com>
#

[ "$INTERFACE" != "mobiledata" ] && exit 0
[ "$ACTION" = "ifup" ] && exit 0
[ "$(cat /tmp/modem_hotplug_running)" = "1" ] && exit 0

echo 1 > /tmp/modem_hotplug_running # Prevent multiple instances from running at the same time

MODEMIFACE="mobiledata"
MODEMINDEX="$(/usr/bin/mmcli -L -K | grep -Eo '/org/freedesktop/.*' | tr -d "'")"

if [ -z "$MODEMINDEX" ]; then
    checkandreconnect
else
    /usr/bin/mmcli -m "$MODEMINDEX" >/tmp/modemStatus
fi

DISABLED=$(grep -w "disabled" /tmp/modemStatus)
SEARCHING=$(grep -w "searching" /tmp/modemStatus)
REGISTERED=$(grep -w "registered" /tmp/modemStatus)
CONNECTED=$(grep -w "connected" /tmp/modemStatus)
IDLE=$(grep -w "idle" /tmp/modemStatus)

checkandreconnect() {
    logger -t INFO "Giving 10 extra seconds to complete modem setup."
    sleep 10
    logger -t INFO "Beginning ping test."
    ping -c3 -s56 -w30 www.telcoantennas.com.au
    if [ $? -eq 0 ]; then
        logger -t INFO "Modem is connected. 3 successful pings."
        echo 0 > /tmp/modem_hotplug_running
    else
        logger -t INFO "Modem failed ping test. Reconnecting."
        /etc/init.d/modemmanager stop && sleep 2 && /etc/init.d/modemmanager start
        sleep 10
        ifup $MODEMIFACE
    fi
}

reconnect() {
    logger -t INFO "Reconnecting modem now."
    /etc/init.d/modemmanager stop && sleep 2 && /etc/init.d/modemmanager start
    sleep 10
    ifup $MODEMIFACE
}

logger -t INFO "Hotplug: Modem Hotplug script is running."

if [ -n "$DISABLED" ]; then
    logger -t INFO "Modem is disabled. Will attempt to initiate connection."
    logger -t DEBUG "$DISABLED"
    reconnect
fi

if [ -n "$CONNECTED" ]; then
    logger -t INFO "Modem reports as connected. Checking actual connectivity."
    checkandreconnect
fi

if [ -n "$SEARCHING" ]; then
    logger -t INFO "Modem is searching."
    checkandreconnect
fi

if [ -n "$IDLE" ]; then
    logger -t INFO "Modem is idle.  Attempting to bring modem back online."
    reconnect
fi

if [ -n "$REGISTERED" ]; then
    logger -t INFO "Modem is registered."
    checkandreconnect
fi

# Any time this script runs, put the current modem and bearer indexes into shared memory, for use by ltestatus and other apps.
mmcli -L -K | awk {i++}i==2 | sed 's/^.*: //' >/tmp/modemIndex
mmcli -m "$(cat /tmp/modemIndex)" -K | grep 'bearers.value\[1\]' | sed 's/^.*: //' >/tmp/bearerIndex
logger -t INFO "Modem hotplug script ran."
